# Generated by Django 4.2 on 2023-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
