# Generated by Django 4.2 on 2023-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
